# -*- coding: utf-8 -*-
"""B19EE046_A34_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Rebc10Vz5Na7rttBNCKK6hu6u1rwaVZ
"""

!git clone https://github.com/oscarknagg/few-shot.git

from google.colab import drive
drive.mount('/content/drive')

cd drive

cd MyDrive

!mkdir "B19EE046_Q2"

cd B19EE046_Q2

cd few-shot

!git clone https://github.com/brendenlake/omniglot.git

cd scripts

!pip install -r requirements.txt

!python prepare_omniglot.py

cd drive/MyDrive

cd B19EE046_Q2

cd few-shot

!pip install -r requirements.txt

!python -m experiments.proto_nets --dataset omniglot --k-test 5 --n-test 1

!python -m experiments.proto_nets --dataset omniglot --k-test 5 --n-test 5

!python -m experiments.proto_nets --dataset omniglot --k-test 20 --n-test 1

!python -m experiments.proto_nets --dataset omniglot --k-test 20 --n-test 5 --n-train 5

!python -m experiments.proto_nets --dataset omniglot --k-test 10 --n-test 1

!python -m experiments.proto_nets --dataset omniglot --k-test 10 --n-test 5

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 5 --n-test 1

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 5 --n-test 5

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 20 --n-test 1

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 20 --n-test 5

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 10 --n-test 1

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 10 --n-test 5

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 20 --n-test 5 --n-train 5

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 20 --n-test 5 --n-train 10

!python -m experiments.proto_nets --dataset omniglot --distance 'cosine' --k-test 20 --n-test 5 --n-train 15

!python -m experiments.proto_nets --dataset omniglot --k-test 20 --n-test 5 --n-train 10

!python -m experiments.proto_nets --dataset omniglot --k-test 20 --n-test 5 --n-train 15
