# -*- coding: utf-8 -*-
"""B19EE046_A34_Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2J4WCudMypLaWhb3g01oXxlckw9Vt7j
"""

from google.colab import drive
drive.mount('/content/drive')

cd '/content/drive/MyDrive/B19EE046_Q4'

!git clone https://github.com/salesforce/awd-lstm-lm.git

!git clone https://github.com/quark0/darts.git

cd awd-lstm-lm

!bash getdata.sh

cd rnn

!python test.py --data '/content/drive/MyDrive/B19EE046_Q4/awd-lstm-lm/data/penn/' --model_path '/content/drive/MyDrive/B19EE046_Q4/darts/rnn/ptb_model.pt'

import torchvision
trainset = torchvision.datasets.CIFAR10(root='/content/drive/MyDrive/B19EE046_Q4/darts/data/cifar10', train=True,download=True)
testset = torchvision.datasets.CIFAR10(root='/content/drive/MyDrive/B19EE046_Q4/darts/data/cifar10', train=False,download=True)

!python test.py --auxiliary --model_path '/content/drive/MyDrive/B19EE046_Q4/darts/cnn/cifar10_model.pt'

!python train_search.py --unrolled

!python train_search.py --data '/content/drive/MyDrive/B19EE046_Q4/awd-lstm-lm/data/penn/' --unrolled

cd darts

cd cnn

!python train.py --auxiliary --cutout

cd ..

cd rnn

!python train.py --data '/content/drive/.shortcut-targets-by-id/1igaRi_LRURV8nFC-jyoXND54rA2solUZ/B19EE046_Q4/awd-lstm-lm/data/penn'
